[book]
language = "en"
multilingual = false
src = "."
title = "Guide to Utility Development"

[build]
# Let's re-use the existing target dir for all build artifacts.
build-dir = "./target/book"

[output.html]
git-repository-url = "https://github.com/utnet-org/cook-book/tree/main"
edit-url-template = "https://github.com/utnet-org/cook-book/edit/main/{path}"
